config/routes.rb
NewsApp::Application.routes.draw do
  resources :requirements

  get "news/display"

end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
  attr_accessible :describtion, :points
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def display
  	@ballroom = "Ballroom Dance News"
  	@modern = "Modern Dance News"
  	@ballet = "Ballet News"
  	@zumba = "Zumba News"

  end
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
  # GET /requirements
  # GET /requirements.json
  def index
    @requirements = Requirement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requirements }
    end
  end

  # GET /requirements/1
  # GET /requirements/1.json
  def show
    @requirement = Requirement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @requirement }
    end
  end

  # GET /requirements/new
  # GET /requirements/new.json
  def new
    @requirement = Requirement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @requirement }
    end
  end

  # GET /requirements/1/edit
  def edit
    @requirement = Requirement.find(params[:id])
  end

  # POST /requirements
  # POST /requirements.json
  def create
    @requirement = Requirement.new(params[:requirement])

    respond_to do |format|
      if @requirement.save
        format.html { redirect_to @requirement, notice: 'Requirement was successfully created.' }
        format.json { render json: @requirement, status: :created, location: @requirement }
      else
        format.html { render action: "new" }
        format.json { render json: @requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requirements/1
  # PUT /requirements/1.json
  def update
    @requirement = Requirement.find(params[:id])

    respond_to do |format|
      if @requirement.update_attributes(params[:requirement])
        format.html { redirect_to @requirement, notice: 'Requirement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requirements/1
  # DELETE /requirements/1.json
  def destroy
    @requirement = Requirement.find(params[:id])
    @requirement.destroy

    respond_to do |format|
      format.html { redirect_to requirements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper

	def image_tag(path)
		out = "<img src=#{path} class='img-rounded'>"
		out.html_safe
	end


	def table_helper

		out = "<h4>Requirements table</h4> <span class = 'label label-important'>Requirements</span><table class = 'table-striped table-bordered'>"
		Requirement.find_each do |requirement|
			out = out + "<tr><td>#{requirement[:describtion]}</td><td>#{requirement[:points]}</td></tr>"
		end
		out = out + "</table>"
		out.html_safe
	end
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/news/display.html.erb
<div "container-fluid" class>
    <div class="row-fluid">
        <div class="span12" id="main-panel">
            <div class="page-header">
                <br>Dance News</br>
            </div>
        <div class="row-fluid">
            <div class="span9">
                <div class="row-fluid">



                    <ul class="nav nav-tabs">
                        <li>
                            <a data-toggle="tab" class="btn btn-large btn-primary" href="#tab1"><abbr title="Ballet Dance">Ballet</abbr></a>
                        </li>
                        <li>
                            <a data-toggle="tab" class="btn btn-large btn-primary" href="#tab2"><abbr title="Modern Dance">Modern</abbr></a>
                        </li>
                        <li>
                            <a data-toggle="tab" class="btn btn-large btn-primary" href="#tab3"><abbr title="Zumba Dance">Zumba</abbr></a>
                        </li>
                        <li>
                            <a data-toggle="tab" class="btn btn-large btn-primary" href="#tab4"><abbr title="Ballroom Dance">Ballroom</abbr></a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane" id="tab1">
                            <p><%=@ballet %></p>
                            <%=image_tag("/assets/onegin.jpg") %>
                        </div>
                        <div class="tab-pane" id="tab2">
                            <p><%=@modern %></p>
                        </div>
                        <div class="tab-pane" id="tab3">
                            <p><%=@zumba %></p>
                        </div>
                        <div class="tab-pane" id="tab4">
                            <p><%=@ballroom %></p>
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12" id="main-content">
                        <%=table_helper %>
                    </div>
                </div>
                <div class="row-fluid"></div>
            </div>
        </div>
    </div>
</div>
</div>

app/views/requirements/_form.html.erb
<%= form_for(@requirement) do |f| %>
  <% if @requirement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@requirement.errors.count, "error") %> prohibited this requirement from being saved:</h2>

      <ul>
      <% @requirement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :describtion %><br />
    <%= f.text_field :describtion %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.number_field :points %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requirements/edit.html.erb
<h1>Editing requirement</h1>

<%= render 'form' %>

<%= link_to 'Show', @requirement %> |
<%= link_to 'Back', requirements_path %>

app/views/requirements/index.html.erb
<h1>Listing requirements</h1>

<table>
  <tr>
    <th>Describtion</th>
    <th>Points</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @requirements.each do |requirement| %>
  <tr>
    <td><%= requirement.describtion %></td>
    <td><%= requirement.points %></td>
    <td><%= link_to 'Show', requirement %></td>
    <td><%= link_to 'Edit', edit_requirement_path(requirement) %></td>
    <td><%= link_to 'Destroy', requirement, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Requirement', new_requirement_path %>

app/views/requirements/new.html.erb
<h1>New requirement</h1>

<%= render 'form' %>

<%= link_to 'Back', requirements_path %>

app/views/requirements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Describtion:</b>
  <%= @requirement.describtion %>
</p>

<p>
  <b>Points:</b>
  <%= @requirement.points %>
</p>


<%= link_to 'Edit', edit_requirement_path(@requirement) %> |
<%= link_to 'Back', requirements_path %>